language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t shomarov/fullstackopen-2019-project-prisma ./prisma
  - docker build -t shomarov/fullstackopen-2019-project-api ./api
  - docker build -t shomarov/fullstackopen-2019-project-client ./client
  - docker build -t shomarov/fullstackopen-2019-project-nginx ./nginx

after_success:
  - echo "$DOKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push shomarov/fullstackopen-2019-project-prisma
  - docker push shomarov/fullstackopen-2019-project-api
  - docker push shomarov/fullstackopen-2019-project-client
  - docker push shomarov/fullstackopen-2019-project-nginx

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: eu-central-1
  app: fullstackopen-2019-project
  env: Fullstackopen2019Project-env
  bucket_name: elasticbeanstalk-eu-central-1-801956187188
  bucket_path: fullstackopen-2019-project
  on:
    branch: master
