sudo: required
services:
  - docker

before_install:
  - docker build -t shomarov/fullstackopen-2019-project-prisma ./prisma
  - docker build -t shomarov/fullstackopen-2019-project-api ./api
  - docker build -t shomarov/fullstackopen-2019-project-client ./client
  - docker build -t shomarov/fullstackopen-2019-project-nginx ./nginx

after_success:
  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
  - docker push shomarov/fullstackopen-2019-project-prisma
  - docker push shomarov/fullstackopen-2019-project-api
  - docker push shomarov/fullstackopen-2019-project-client
  - docker push shomarov/fullstackopen-2019-project-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app:
  env:
  bucket_name: elasticbeanstalk-us-east-1-630186264736
  bucket_path:
  on:
    branch: master
  access_key_id: $aws_access_key_id
  secret_access_key:
    secure: $aws_secret_access_key
