version: '3.7'
volumes:
  mongodb:
services:
  mongodb:
    build:
      dockerfile: Dockerfile.dev
      context: ./mongodb
    image: shomarov/mongodb
    container_name: mongodb
    env_file: ./mongodb/.env
    volumes:
      - mongodb:/data/db
    ports:
      - 27017-27019:27017-27019
    restart: always
  server:
    container_name: server
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    image: shomarov/server
    volumes:
      - /server/node_modules
      - ./server:/server
    ports:
      - 5000:5000
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
    restart: unless-stopped
  client:
    container_name: client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    image: shomarov/client
    volumes:
      - /client/node_modules
      - ./client:/client
    ports:
      - 3000:3000
    depends_on:
      - server
    restart: unless-stopped
