version: '3.7'
volumes:
  mongo:
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - 27017:27017
    volumes:
      - mongo:/var/lib/mongo
  prisma:
    image: prismagraphql/prisma:1.34
    container_name: prisma
    restart: always
    ports:
      - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo/
    depends_on:
      - mongo
  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    image: shomarov/api
    volumes:
      - /api/node_modules
      - ./api:/api
    command: >
      sh -c "./wait-for prisma:4466 --
             echo Connection to Prisma is up. &&
             prisma deploy -p prisma.test.yml &&
             prisma deploy -p prisma.dev.yml &&
             npm run dev"
    ports:
      - 4000:4000
    depends_on:
      - prisma
    restart: unless-stopped
  client:
    container_name: client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    image: shomarov/client
    volumes:
      - /client/node_modules
      - ./client:/client
    ports:
      - 3000:3000
    depends_on:
      - api
    restart: unless-stopped
