version: '3.7'
services:
  mongo:
    build:
      dockerfile: Dockerfile.dev
      context: ./mongo
    image: shomarov/mongo
    container_name: mongo
    env_file: ./mongo/.env
    volumes:
      - ./mongo/data/:/data/db
    ports:
      - 27017-27019:27017-27019
    restart: always
  server:
    container_name: server
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    image: shomarov/server
    volumes:
      - /server/node_modules
      - ./server:/server
    ports:
      - 5000:5000
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    restart: unless-stopped
  app:
    container_name: app
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    image: shomarov/app
    volumes:
      - /app/node_modules
      - ./app:/app
    ports:
      - 3000:3000
    depends_on:
      - server
    restart: unless-stopped
