version: '3.7'
services:
  mongo:
    build:
      dockerfile: Dockerfile.dev
      context: ./mongo
    image: shomarov/mongo
    container_name: mongo
    env_file: ./mongo/.env
    volumes:
      - ./mongo/data/:/data/db
    ports:
      - 27017-27019:27017-27019
    restart: always
  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    image: shomarov/api
    volumes:
      - /api/node_modules
      - ./api:/api
    ports:
      - 5000:5000
    env_file:
      - ./api/.env
    depends_on:
      - mongo
    restart: unless-stopped
  app:
    container_name: app
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    image: shomarov/app
    volumes:
      - /app/node_modules
      - ./app:/app
    ports:
      - 3000:3000
    depends_on:
      - api
    restart: unless-stopped
