version: '3.7'
services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: ./api
    image: shomarov/fullstackopen-2019-project-api
    restart: unless-stopped
  client:
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./client
    image: shomarov/fullstackopen-2019-project-client
    depends_on:
      - api
    restart: unless-stopped
  nginx:
    container_name: nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    image: shomarov/fullstackopen-2019-project-nginx
    depends_on:
      - client
    restart: always
