put http://localhost:5000/api/recipes/5e2e992a39ded20150999794
Content-Type: application/json

{
    "ingredients": [
      "400g can chickpea, rinsed and drained",
      "1 small red onion, roughly chopped",
      "1 garlic clove, chopped",
      "handful of flat-leaf parsley or curly parsley",
      "1 tsp ground cumin",
      "1 tsp ground coriander",
      "1⁄2 tsp harissa paste or chilli powder",
      "2 tbsp plain flour",
      "2 tbsp sunflower oil",
      "toasted pitta bread, to serve",
      "200g tub tomato salsa, to serve",
      "green salad, to serve"
    ],
    "notes": [
      "want this",
      "new note"
    ],
    "title": "Falafel burgers",
    "description": "A healthy burger that's filling too. These are great for anyone who craves a big bite but doesn't want the calories",
    "time": 20,
    "difficulty": "easy",
    "source": "https://www.bbcgoodfood.com/recipes/falafel-burgers-0",
    "id": "5e2e992a39ded20150999794"
  }