POST http://localhost:5000/auth/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlNDQwMGYzYjcxZDE3MDIzMGI5ZTcxNyIsInVzZXJuYW1lIjoidXNlciIsImlhdCI6MTU4MTU0MDY2MX0.BhrAjgf_cfGHuCqUiS2RkXqthyHRWM1ZJwB3GG9vZP8
Content-Type: application/json

{
  "oldPassword": "newPassword",
  "newPassword": "password"
}