post http://localhost:5000/api/recipes
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVlMmZmMTgxZmYyZWFlMDBiNzhhNGZkMiIsImlhdCI6MTU4MDIwMTM3NH0.L3uj0AcB2aZgGVwChU8PwLvriq_32AgYrTmA2FHs13E
Content-Type: application/json

{
    "title": "Falafel burgers",
    "description": "A healthy burger that's filling too. These are great for anyone who craves a big bite but doesn't want the calories",
    "time": "20",
    "difficulty": "easy",
    "ingredients": [
      "400g can chickpea, rinsed and drained",
      "1 small red onion, roughly chopped",
      "1 garlic clove, chopped",
      "handful of flat-leaf parsley or curly parsley",
      "1 tsp ground cumin",
      "1 tsp ground coriander",
      "1⁄2 tsp harissa paste or chilli powder",
      "2 tbsp plain flour",
      "2 tbsp sunflower oil",
      "toasted pitta bread, to serve",
      "200g tub tomato salsa, to serve",
      "green salad, to serve"
    ],
    "instructions": [
      "Drain a 400g can chickpeas and pat dry with kitchen paper.",
      "Tip into a food processor along with 1 small roughly chopped red onion, 1 garlic clove, handful of flat-leaf parsley, 1 tsp ground cumin, 1 tsp ground coriander, ½ tsp harissa paste or chillli powder, 2 tbsp plain flour and a little salt.",
      "Blend until fairly smooth, then shape into four patties with your hands.",
      "Heat 2 tbsp sunflower oil in a non-stick frying pan, add the burgers, then quickly fry for 3 mins on each side until lightly golden.",
      "Serve with toasted pitta bread, 200g tub tomato salsa and a green salad."
    ],
    "notes": [
      "want this"
    ],
    "source": "https://www.bbcgoodfood.com/recipes/falafel-burgers-0",
    "userId": "5e2f57e581fb3f039f40c6c5"
  }